version: '3.1'

services:
  postgres:
    image: postgres:11
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54330:5432
    expose:
      - 54330
    volumes:
      - ~/zookeeping-pg:/var/lib/postgresql/data

  zookeeping:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zookeeping
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./src:/home/node/app/src

    networks:
      - default
    command: npm run localhost:docker
